### ISSUE TITLE
Detach ArrayBuffer on Node side

### ISSUE THREAD

**Issue by chung-leong** [chung-leong/zigar#229]
Not sure how ArrayBuffers can become detached in Node but it's happening (in Node 18):

```
  1) Integration tests (node-zigar, Debug)
       Variables
         should import struct with comptime fields:
     TypeError: Cannot perform DataView constructor on a detached ArrayBuffer
      at new DataView (<anonymous>)
      at NodeEnvironment.obtainFixedView (<anonymous>:4509:14)
      at NodeEnvironment.createView (<anonymous>:3987:21)
      at NodeEnvironment.invokeFactory (<anonymous>:4570:28)
      at load (file:///home/cleong/zigar/node-zigar-addon/dist/index.js:7:10)
      at async loadZig (file:///home/cleong/zigar/node-zigar/dist/index.js:39:18)
      at async nextLoad (node:internal/modules/esm/loader:163:22)
      at async ESMLoader.load (node:internal/modules/esm/loader:603:20)
      at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11)
      at async link (node:internal/modules/esm/module_job:68:21)
```

**Comment by chung-leong** [comment]
Due to attempts at creating zero-length external buffers.
