### ISSUE TITLE
Failing test case: pass allocator as argument and return a new slice

### ISSUE THREAD

**Issue by chung-leong** [chung-leong/zigar#484]
This happens when optimize = ReleaseSmall or ReleaseFast:
```
Error: Unknown failure
    at constructor.obtainExternView (<anonymous>:2536:29)
    at constructor.obtainZigView (<anonymous>:2473:19)
    at constructor.findMemory (<anonymous>:2455:19)
    at []const u8.updateTarget (<anonymous>:5368:34)
    at Proxy.callback (<anonymous>:2779:28)
    at Proxy.visitPointer (<anonymous>:5700:8)
    at Arg(fn (Allocator) []const u8).visitPointers (<anonymous>:3728:25)
    at constructor.updatePointerTargets (<anonymous>:2795:18)
    at handler (<anonymous>:1837:18)
    at constructor.runFunction (<anonymous>:1919:14)
    at constructor.performJsAction (<anonymous>:1901:25)
    at constructor.invokeThunk (<anonymous>:2020:14)
    at call (<anonymous>:1947:19)
    at file:///home/cleong/zigar/zigar-compiler/test/integration/function-pointer/tests.js:96:9
    at capture (file:///home/cleong/zigar/zigar-compiler/test/integration/test-utils.js:11:11)
    at Context.<anonymous> (file:///home/cleong/zigar/zigar-compiler/test/integration/function-pointer/tests.js:95:30)
Aborted (core dumped)
```
But not what the test case in question runs by itself.

**Comment by chung-leong** [comment]
Test does fail in isolation and in debug mode:
```
error(gpa): Allocation alignment 8 does not match free alignment 1. Allocation: 
 Free: 
/home/cleong/zigar/zigar-compiler/test/integration/function-pointer/returning-slice.zig:8:25: 0x7f29e160c457 in call (returning-slice)
    defer allocator.free(s);
                        ^
/home/cleong/zigar/zigar-compiler/zig/thunk-zig.zig:37:13: 0x7f29e1666c64 in invokeFunction (returning-slice)
            const retval = @call(.auto, function, args);
            ^
/home/cleong/zigar/zigar-compiler/zig/host-napi.zig:342:21: 0x7f29e1600577 in runThunk (returning-slice)
    return if (thunk(fn_ptr, arg_ptr)) .ok else |_| .failure;
                    ^
???:?:?: 0x7f2a0805a24d in ??? (linux.x64.node)
???:?:?: 0xf29f4e in ??? (???)
???:?:?: 0xf2a7bc in ??? (???)
```

**Comment by chung-leong** [comment]
It's still failing.

**Comment by chung-leong** [comment]
It has something to do with uninitialized pointer.
