### ISSUE TITLE
Failing test case: call variadic functions

### ISSUE THREAD

**Issue by chung-leong** [chung-leong/zigar#489]
```
  1) Integration tests (rollup-plugin-zigar, Debug)
       Function calling
         should call variadic functions:
     RuntimeError: table index is out of bounds
      at call-variadic-functions.wasm.variadic.call__anon_4226 (wasm://wasm/call-variadic-functions.wasm-0045e39a:wasm-function[568]:0x2c40f)
      at call-variadic-functions.wasm.thunk-zig.createThunk__anon_3715.ns_variadic.invokeFunction (wasm://wasm/call-variadic-functions.wasm-0045e39a:wasm-function[436]:0x2369f)
      at call-variadic-functions.wasm.runVariadicThunk (wasm://wasm/call-variadic-functions.wasm-0045e39a:wasm-function[42]:0x276a)
      at constructor.runVariadicThunk (file:///tmp/rollup-integration-test/Debug/4125e55965f7acdd58ced9025d3be862.mjs:1815:27)
      at constructor.invokeThunk (file:///tmp/rollup-integration-test/Debug/4125e55965f7acdd58ced9025d3be862.mjs:1223:12)
      at printIntegers (file:///tmp/rollup-integration-test/Debug/4125e55965f7acdd58ced9025d3be862.mjs:1143:17)
      at file:///home/cleong/zigar/zigar-compiler/test/integration/function-calling/tests.js:556:42
      at capture (file:///home/cleong/zigar/zigar-compiler/test/integration/test-utils.js:11:11)
      at Context.<anonymous> (file:///home/cleong/zigar/zigar-compiler/test/integration/function-calling/tests.js:556:28)
```

**Comment by chung-leong** [comment]
Crashing in Node as well.

**Comment by chung-leong** [comment]
Still crashing in Node on MacOS.

**Comment by chung-leong** [comment]
Closed by accident.
